# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69a208cdab89ce2b90e5a1083b7b786e27d0ade8f8cfe91bb594dd6155aa650d5f5130c6ae6b68fb4ac0a8549642ff9aa9d91f305efc4916565f88366d1c9c22

test:
  secret_key_base: 4b37eb530228566bf2c7b8f914e3049a6320e1f498715ab5ee5afcc38568730cb35faa9616c3e50f14086c0c7c07ce636ff994be0045498c62d2cc68ba7b5d1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
